name = "sag-abi-mediation-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

# WICHTIG: Auf eure Domain setzen, z.B. "https://abitrainer.sanktannagymnasium.de"
# Solange "*" steht, kann jede Website die API nutzen!
[vars]
ALLOWED_ORIGIN = "https://myabiflow.de"

[[kv_namespaces]]
binding = "RESULTS_KV"
id = "e3642743a28c40b3919f57cc1de33f14"